project:
  type: website
  output-dir: docs

website:
  title: "Md Nakir Ahmed"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.pdf
      - text: "Class Presentations"
        menu:
          - text: "Prepare for class 1"
            href: Prepareforclass01_Nakir.pdf
          - text: "Prepare for class 2"
            href: Prepareforclass02_Nakir.pdf
          - text: "Prepare for class 3"
            href: Prepareforclass03_Nakir.pdf
          - text: "Prepare for class 4"
            href: Prepareforclass04_Nakir.pdf
          - text: "Prepare for class 5"
            href: Prepareforclass05_Nakir.pdf
          - text: "Prepare for class 6"
            href: Prepareforclass06_Nakir.pdf
          - text: "Prepare for class 7"
            href: Prepareforclass07_Nakir.pdf
      - text: "Assignments"
        menu:
          - text: "Assignment 01"
            href: assignment01_Nakir.pdf
          - text: "Assignment 02"
            href: assignment02_Nakir.pdf
          - text: "Assignment 03"
            href: assignment03_Nakir.pdf
          - href: assignment04_Nakir.qmd
            text: "Assignment 04"
      - text: "Final Project"
        menu:
          - text: "Final Project Proposal"
            href: Ahmed_FinalProject_Proposal_Report-merged.pdf
          - text: "Final Project Progress"
            href: KM_Project_Progress_Nakir.pdf
          - text: "Final Project Presentation"
            href: Nakir_Final_Project_Presesntation.pdf
          - text: "Final Project Document"
            href: Nakir_Final_Project_Report.pdf


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
